# Force enabling of Ubuntu 14.04
sudo: required
dist: trusty

before_install:
    # Need to install CMake v3.2 to get C++11 features
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo apt-get update
    - sudo apt-get install cmake

    - sudo apt-get install -y m4 build-essential gfortran freeglut3-dev qt4-dev-tools libgmp3-dev libmpfr-dev libboost-all-dev
    - sudo apt-get install libeigen3-dev xorg-dev libglu1-mesa-dev

    # Ubuntu does not provide libboost_thread-mt because fuck you that's why
    # We need to link libboost_thread-mt to libboost_thread to fix this.
    - sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_thread.so /usr/lib/x86_64-linux-gnu/libboost_thread-mt.so
    - sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_thread.a /usr/lib/x86_64-linux-gnu/libboost_thread-mt.a

    # Get CGAL source and install it (4.8.1, this should be relatively quick)
    - wget https://github.com/CGAL/cgal/archive/releases/CGAL-4.8.1.tar.gz
    - tar xf CGAL-4.8.1.tar.gz
    - cd cgal-releases-CGAL-4.8.1
    - cmake .
    - make
    - sudo make install
    - cd ..

# Enable C++ support
# Note: this doesn't appear to actually use the specified compilers
# but it means that the compilers that are actually used end up
# being fresh enough (g4.8+ and c3.5+) that c++11 will mostly
# compile.
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
