# Force enabling of Ubuntu 14.04
sudo: required
dist: trusty

# Doesn't seem to be working
#addons:
#  packages:
#    - g++
#    - libcgal-dev


before_install:
    - sudo apt-get install -y libcgal-dev
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
